export const enum PolicyType {
  LIBERAL = "LIBERAL",
  FASCIST = "FASCIST",
  COMMUNIST = "COMMUNIST",
  ANTIFASCIST = "ANTIFASCIST",
  ANTICOMMUNIST = "ANTICOMMUNIST",
  SOCIODEMOCRATIC = "SOCIALDEMOCRATIC",
}

export const enum Role {
  LIBERAL = "LIBERAL",
  FASCIST = "FASCIST",
  HITLER = "HITLER",
  COMMUNIST = "COMMUNIST",
  MONARCHIST = "MONARCHIST",
  ANARCHIST = "ANARCHIST",
}
